/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pattinaggio;

import java.io.IOException;

/**
 *
 * @author paolucci.sara
 */
public class FormGioco extends javax.swing.JFrame {
    private Pattinatore nome;
    private String musica,nickname;
    private Gestore g;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGioco.class.getName());

    /**
     * Creates new form FormGioco
     * @param nome
     * @param musica
     * @param nickname
     */
    public FormGioco(Pattinatore nome, String musica,String nickname) {
        initComponents();
        this.nome = nome;
        this.musica = musica;
        this.nickname = nickname;
        
        this.g = new Gestore(nome,musica,nickname);
        lblNickname.setText(g.getNickname());
        txtArea.setText("Benvenuto\n\n");
        btnAbSpeciale.setEnabled(false);
        btnValutazioni.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblTurno = new javax.swing.JLabel();
        lblPunti = new javax.swing.JLabel();
        btnAvanti = new javax.swing.JButton();
        btnRischio = new javax.swing.JButton();
        btnAbSpeciale = new javax.swing.JButton();
        btnIstruzioni3 = new javax.swing.JButton();
        lblNickname = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnScontroDiretto = new javax.swing.JButton();
        btnValutazioni = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblPersonaggio = new javax.swing.JLabel();
        lblEvento = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 219, 219));

        lblTurno.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurno.setText("Turno 0");
        lblTurno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPunti.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblPunti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPunti.setText("Punti: 0");

        btnAvanti.setBackground(new java.awt.Color(153, 204, 255));
        btnAvanti.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        btnAvanti.setForeground(new java.awt.Color(0, 51, 204));
        btnAvanti.setText("Avanti");
        btnAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvantiActionPerformed(evt);
            }
        });

        btnRischio.setBackground(new java.awt.Color(153, 204, 255));
        btnRischio.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        btnRischio.setForeground(new java.awt.Color(0, 51, 204));
        btnRischio.setText("Rischio");
        btnRischio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRischioActionPerformed(evt);
            }
        });

        btnAbSpeciale.setBackground(new java.awt.Color(153, 204, 255));
        btnAbSpeciale.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        btnAbSpeciale.setForeground(new java.awt.Color(0, 51, 204));
        btnAbSpeciale.setText("Abilità Speciale");
        btnAbSpeciale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbSpecialeActionPerformed(evt);
            }
        });

        btnIstruzioni3.setBackground(new java.awt.Color(153, 204, 255));
        btnIstruzioni3.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        btnIstruzioni3.setForeground(new java.awt.Color(0, 51, 204));
        btnIstruzioni3.setText("Salva partita");

        lblNickname.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblNickname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNickname.setText("Nickname");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane3.setViewportView(txtArea);

        btnScontroDiretto.setBackground(new java.awt.Color(153, 204, 255));
        btnScontroDiretto.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        btnScontroDiretto.setForeground(new java.awt.Color(0, 51, 204));
        btnScontroDiretto.setText("Scontro Diretto");
        btnScontroDiretto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScontroDirettoActionPerformed(evt);
            }
        });

        btnValutazioni.setBackground(new java.awt.Color(153, 204, 255));
        btnValutazioni.setFont(new java.awt.Font("Serif", 1, 20)); // NOI18N
        btnValutazioni.setForeground(new java.awt.Color(0, 51, 204));
        btnValutazioni.setText("Valutazioni");
        btnValutazioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValutazioniActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Record");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPersonaggio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNickname, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(lblPunti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnValutazioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIstruzioni3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPersonaggio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAvanti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRischio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnScontroDiretto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAbSpeciale)
                    .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnAvanti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnScontroDiretto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRischio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbSpeciale))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNickname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPersonaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPunti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIstruzioni3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnValutazioni))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTurno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvantiActionPerformed
        g.setTurno(g.getTurno()+1);
        lblTurno.setText("Turno "+ g.getTurno());
        String evento = g.Avanti();
        txtArea.append(evento+"\n");
        lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
        if(g.getTurno()==10){
            btnAvanti.setEnabled(false);
            btnRischio.setEnabled(false);
            btnAbSpeciale.setEnabled(false);
            btnScontroDiretto.setEnabled(false);
            btnValutazioni.setEnabled(true);
        }
    }//GEN-LAST:event_btnAvantiActionPerformed

    private void btnScontroDirettoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScontroDirettoActionPerformed
        g.setTurno(g.getTurno()+1);
        lblTurno.setText("Turno "+ g.getTurno());
        try {
            String scontro = g.scontroDiretto();
            txtArea.append(scontro+"\n");
            lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
            btnScontroDiretto.setEnabled(false);
        } catch (IOException ex) {
            System.getLogger(FormGioco.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        if(g.getTurno()==10){
            btnAvanti.setEnabled(false);
            btnRischio.setEnabled(false);
            btnAbSpeciale.setEnabled(false);
            btnScontroDiretto.setEnabled(false);
            btnValutazioni.setEnabled(true);
        }
    }//GEN-LAST:event_btnScontroDirettoActionPerformed

    private void btnRischioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRischioActionPerformed
        g.setTurno(g.getTurno()+1);
        lblTurno.setText("Turno "+ g.getTurno());
        btnAbSpeciale.setEnabled(true);
        String rischio = g.rischio();
        txtArea.append(rischio+"\n");
        lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
        if(g.getTurno()==10){
            btnAvanti.setEnabled(false);
            btnRischio.setEnabled(false);
            btnAbSpeciale.setEnabled(false);
            btnScontroDiretto.setEnabled(false);
            btnValutazioni.setEnabled(true);
        }
    }//GEN-LAST:event_btnRischioActionPerformed

    private void btnAbSpecialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbSpecialeActionPerformed
        g.setTurno(g.getTurno()+1);
        lblTurno.setText("Turno "+ g.getTurno());
        String AbSpeciale = g.abilitaSpeciale();
        txtArea.append(AbSpeciale+"\n");
        lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
        btnAbSpeciale.setEnabled(false);
        if(g.getTurno()==10){
            btnAvanti.setEnabled(false);
            btnRischio.setEnabled(false);
            btnAbSpeciale.setEnabled(false);
            btnScontroDiretto.setEnabled(false);
            btnValutazioni.setEnabled(true);
        }
    }//GEN-LAST:event_btnAbSpecialeActionPerformed

    private void btnValutazioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValutazioniActionPerformed
        g.setValutazioni(g.getValutazioni()+1);
        if(g.getValutazioni()==1){
            String valutazione = g.skatingSkillsValutazione();
            txtArea.append(valutazione);
            lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
        }
        else if(g.getValutazioni()==2){
            String valutazione = g.transitionsValutazione();
            txtArea.append(valutazione);
            lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
        }
        else if(g.getValutazioni()==3){
            String valutazione = g.performanceValutazione();
            txtArea.append(valutazione);
            lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
        }
        else if(g.getValutazioni()==4){
            String valutazione = g.compositionValutazione();
            txtArea.append(valutazione);
            lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
        }
        else{
            String valutazione = g.interpretationOfMusicValutazione();
            txtArea.append(valutazione);
            lblPunti.setText("Punti: "+ g.getPersonaggio().punti);
            btnValutazioni.setEnabled(false);
        }
    }//GEN-LAST:event_btnValutazioniActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbSpeciale;
    private javax.swing.JButton btnAvanti;
    private javax.swing.JButton btnIstruzioni3;
    private javax.swing.JButton btnRischio;
    private javax.swing.JButton btnScontroDiretto;
    private javax.swing.JButton btnValutazioni;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblEvento;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblPersonaggio;
    private javax.swing.JLabel lblPunti;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
