/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pattinaggio;

import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author paolucci.sara
 */
public class FormMusica extends javax.swing.JFrame {
    private String musica,nickname;
    private Pattinatore nome;
    private Clip clip;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMusica.class.getName());

    /**
     * Creates new form FormMusica
     * @param nome
     */
    public FormMusica(Pattinatore nome,String nickname) {
        initComponents();
        this.nome = nome;
        this.nickname=nickname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSkyfall = new javax.swing.JButton();
        btnLoveGame = new javax.swing.JButton();
        btnPrayForMe = new javax.swing.JButton();
        btnEBYT = new javax.swing.JButton();
        btnPlaySkyfall = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPlayLoveGame = new javax.swing.JButton();
        btnPlayPrayForMe = new javax.swing.JButton();
        btnEveryBreathYouTake = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(195, 216, 216));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 360));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Musica");

        btnSkyfall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/skyfall.jpg"))); // NOI18N
        btnSkyfall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkyfallActionPerformed(evt);
            }
        });

        btnLoveGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lovegame.jpg"))); // NOI18N
        btnLoveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoveGameActionPerformed(evt);
            }
        });

        btnPrayForMe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prayforme.jpg"))); // NOI18N
        btnPrayForMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrayForMeActionPerformed(evt);
            }
        });

        btnEBYT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/everybreathyoutake.jpg"))); // NOI18N
        btnEBYT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEBYTActionPerformed(evt);
            }
        });

        btnPlaySkyfall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barrra.jpg"))); // NOI18N
        btnPlaySkyfall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySkyfallActionPerformed(evt);
            }
        });

        btnPlayLoveGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barrra.jpg"))); // NOI18N
        btnPlayLoveGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayLoveGameActionPerformed(evt);
            }
        });

        btnPlayPrayForMe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barrra.jpg"))); // NOI18N
        btnPlayPrayForMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPrayForMeActionPerformed(evt);
            }
        });

        btnEveryBreathYouTake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barrra.jpg"))); // NOI18N
        btnEveryBreathYouTake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEveryBreathYouTakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPlaySkyfall, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnSkyfall, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoveGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayLoveGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPlayPrayForMe, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPrayForMe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(btnEBYT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEveryBreathYouTake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoveGame, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrayForMe, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEBYT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlayLoveGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlayPrayForMe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEveryBreathYouTake, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSkyfall, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlaySkyfall, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkyfallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkyfallActionPerformed
        musica = "skyfall";
        FormGioco f;
        try {
            f = new FormGioco(nome,musica,nickname);
            f.setVisible(true);
        } catch (IOException ex) {
            System.getLogger(FormMusica.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        this.setVisible(false);
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
    }//GEN-LAST:event_btnSkyfallActionPerformed

    private void btnLoveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoveGameActionPerformed
        musica = "loveGame";
        FormGioco f;
        try {
            f = new FormGioco(nome,musica,nickname);
            f.setVisible(true);
        } catch (IOException ex) {
            System.getLogger(FormMusica.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        this.setVisible(false);
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
    }//GEN-LAST:event_btnLoveGameActionPerformed

    private void btnPrayForMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrayForMeActionPerformed
        musica = "prayForMe";
        FormGioco f;
        try {
            f = new FormGioco(nome,musica,nickname);
            f.setVisible(true);
        } catch (IOException ex) {
            System.getLogger(FormMusica.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        this.setVisible(false);
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
    }//GEN-LAST:event_btnPrayForMeActionPerformed

    private void btnEBYTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEBYTActionPerformed
        musica = "everyBreathYouTake";
        FormGioco f;
        try {
            f = new FormGioco(nome,musica,nickname);
            f.setVisible(true);
        } catch (IOException ex) {
            System.getLogger(FormMusica.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        this.setVisible(false);
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
    }//GEN-LAST:event_btnEBYTActionPerformed

    private void btnPlaySkyfallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySkyfallActionPerformed
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
        else {
            riproduciWav("skyfall.wav");
        }
    }//GEN-LAST:event_btnPlaySkyfallActionPerformed

    private void btnPlayLoveGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayLoveGameActionPerformed
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
        else {
            riproduciWav("lovegame.wav");
        }
    }//GEN-LAST:event_btnPlayLoveGameActionPerformed

    private void btnPlayPrayForMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPrayForMeActionPerformed
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
        else {
            riproduciWav("prayforme.wav");
        }
    }//GEN-LAST:event_btnPlayPrayForMeActionPerformed

    private void btnEveryBreathYouTakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEveryBreathYouTakeActionPerformed
        if (clip != null && clip.isRunning()) {
            interrompiWav();
        }
        else {
            riproduciWav("everybreathyoutake.wav");
        }
    }//GEN-LAST:event_btnEveryBreathYouTakeActionPerformed
    
    public void riproduciWav(String nomeFile) {
        try {
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(getClass().getResource("/suoni/" + nomeFile));
            this.clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }


        public void interrompiWav() {
            if (this.clip != null && this.clip.isRunning()) {
               clip.stop();             
               clip.setFramePosition(0); 
            }
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEBYT;
    private javax.swing.JButton btnEveryBreathYouTake;
    private javax.swing.JButton btnLoveGame;
    private javax.swing.JButton btnPlayLoveGame;
    private javax.swing.JButton btnPlayPrayForMe;
    private javax.swing.JButton btnPlaySkyfall;
    private javax.swing.JButton btnPrayForMe;
    private javax.swing.JButton btnSkyfall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
